version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/python-flask-service/
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/codestar_remote_access
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: root
